language: python
python:
  - '3.8.3'

services:
  - postgresql

before_script:
  - psql -c 'create database test;' -U postgres
  - psql -c "ALTER USER postgres PASSWORD 'bubo';" -U postgres
  - psql -c 'GRANT ALL PRIVILEGES ON DATABASE test TO postgres;' -U postgres

env:
  global:
    - DB_NAME: test
    - DB_USER: postgres
    - DB_PASSWORD: bubo
    - DB_HOST: 127.0.0.1
    - language: es-ES

install:
  - pip install poetry
  - poetry install

script:
  - poetry run src/database/bdinitializer.py
  - poetry run task test
