language: python
python:
  - '3.8'
  - '3.8.3'

services:
  - postgresql

before_script:
  - psql -c 'create database test;' -U postgres
  - psql -c "ALTER USER postgres PASSWORD 'bubo';" -U postgres
  - psql -c 'GRANT ALL PRIVILIGES ON test TO postgres;'

env:
  global:
  - DB_NAME = test
  - DB_USER = postgres
  - DB_PASSWORD = bubo
  - DB_HOST = 127.0.0.1
  - secure: ei4TdjQuZox0vlI1vT/MkXNselpt6jA9YYJPEmo5v7B/NcJoYx8+yDuUDOKLfuuPSO8S9qhI+lA4ubZdDBAuxnX7/RsbEbvnSRfDVq7094oh6Z/0Zr3w8YRduueEaXnQsbr9yN5cpC8czJ0qPEps/F/f9luzoagcdv8OYDwRGO22MAiqUNuJmHMRJdnIwZH7p/9y2tJaS28qVnwpJpk1q3TJTDbC2TSV13L9WxJoM3CSh81N5EHHw2cB6/niXOOD+p//VP+0nb4KdrYWikHSysNln72bqTFxwfcqk/YPqxviw3MguHt8wxUtYRRvFGt0+dnn7nCh9rKPws7EHjugOxgQScAKpwNcrAMs5CxAwx+DAOj6EQ1itxs0X8N+QR+Sp2o+swYKn4oZUGbRM+FcDzyMUWiWqOig6HshOX8kU+UFA7tJV8kXJgv37CZ4aphwVSAQYlr5mNjhQvT7tI2qVw1kqnu0yLGe7Ks4aCMDTxrRZDFL462b0PCZEFrENvLPXEbWqLJZKyeV3pqMihI8jAQOLRcmAJXDy0shV113x3s4Y5U6Upryxeb1RLwOCNIOBo4w41fy0g8YpRgfP8HX2yo0QtY4EFs8bvi9Jaq6vw9/KNNHvJdhHfQnWhu48RgYt6gJNlN4rZCeV+M9+eFMlyTSl+/0tr3cUmQeenbLD+Q=

install:
  - pip install poetry
  - poetry install

script:
  - poetry run src/database/bdinitializer.py
  - poetry run task test
